travis:
  secure:
    BINSTAR_TOKEN: iYqnORp9UwvapQbXWYeILTzMjtTK8fCAauzKucVnK+kev9Sug0Kj9FOQ2jD7b8+vL8ol5xUbnCQWVIJrmsGQDTgrp+oL/IDig0U5n4aVFZdlFhABg/s2kozyjdRMWpOGXpcrk8Wb+Gnu5nwN0+NayWInaLknaraCbgJ+LUhCnCFDoAsbTIG2EhLYY7xc5dcmVizuuoRGVHSyQ2+QXceWzG7pBhsSZNwZtSgj9HZ7qkrdc+8MqWO4yeoi81MHNS+lMVeO1IJU7kh/FfTk1TSi3VvY6I+TU2DfLwlewurxWuRo/KLoX0HgK8kMvJqTEA7CbgvtILtPMw7YELTigagektdXh7L76GSeMtV7Y31WuTnQ7MkrG02NaizhGGV7vCe4kXdY45YwhtlRwGf/vzrXcgW9TKVW/K9zhgFd474pCZy1RREJCGFOyQOYGg+TTOuIsgHEYFvudTzhQHtagAMHMtDlEgXbXJTJIBMhgsWXpuN/B8bhUM+k2PsssIjQik9aAN0MmAN9jRClbBx6oPKFAW+A8gP0LhDHqxfr+WnH9JBsq3RyntgcqBnebNeh/7AJIPYM+2VTy82njrI2vlGfG2GlaqK8BFw8W3P61iURd6LGB65imUkc+lS/BimdeVIEwgShpCeXn5MH1cCMoKeuLWqX2uDwMfL55x8vdvanr3Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
